# Generated by Django 3.0.2 on 2020-01-14 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.DateField()),
                ('url', models.TextField()),
                ('image', models.ImageField(upload_to='jackmathews')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jackmathews.Service')),
            ],
        ),
    ]
